spring:
  application:
    name: taskmanager

  datasource:
    url: jdbc:postgresql://localhost:5432/task
    username: task
    password: task
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis

  kafka:
    bootstrap-servers: localhost:29092

  mail:
    to: eduardomaster.tellis@gmail.com
    host: smtp.gmail.com
    port: 587
    username: tcchostphpmail@gmail.com
    password: ggxufhhgpihatdeb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.pw.taskmanager.modules.task.controller,com.pw.taskmanager.modules.shared.presentation
